# lang_dict.py
# Translation dictionary for Box Culvert Design App (Indonesian & English)

lang_dict = {
    "EN": {
        "app_title": "Precast Box Culvert Design",
        "language_select": "🌐 Select Language / Pilih Bahasa",
        "navigation": "📑 Navigation",
        "input_page": "Input Data",
        "calculation_page": "Analysis & Design",
        "output_page": "Reports",
        "input_title": "Input Data - Box Culvert Configuration",
        "calculation_title": "Structural Analysis and Design",
        "output_title": "Reports and Export",
        "geometry_section": "Geometry",
        "material_section": "Materials",
        "loading_section": "Loading",
        "soil_arching_section": "Soil Arching (Marston's Theory)",
        "analysis_section": "2D Frame Analysis",
        "reinforcement_section": "Reinforcement Design",
        "export_report": "Export Reports",
        "word_report": "Word Report",
        "pdf_report": "PDF Report",
        "page_under_development": "This page is under development.",
        "home": "Home",
    },
    "IN": {
        "app_title": "Desain Box Culvert Pracetak",
        "language_select": "🌐 Pilih Bahasa / Select Language",
        "navigation": "📑 Navigasi",
        "input_page": "Data Masukan",
        "calculation_page": "Analisis & Desain",
        "output_page": "Laporan",
        "input_title": "Data Masukan - Konfigurasi Box Culvert",
        "calculation_title": "Analisis Struktur dan Desain",
        "output_title": "Laporan dan Ekspor",
        "geometry_section": "Geometri",
        "material_section": "Material",
        "loading_section": "Pembebanan",
        "soil_arching_section": "Efek Pelengkungan Tanah (Teori Marston)",
        "analysis_section": "Analisis Rangka 2D",
        "reinforcement_section": "Desain Penulangan",
        "export_report": "Ekspor Laporan",
        "word_report": "Laporan Word",
        "pdf_report": "Laporan PDF",
        "page_under_development": "Halaman ini sedang dalam pengembangan.",
        "home": "Beranda",
    }
}
